---
- name: Add MariaDB apt signing key
  ansible.builtin.apt_key:
    url: "https://mariadb.org/mariadb_release_signing_key.asc"
    state: present

- name: Add MariaDB PPA
  ansible.builtin.apt_repository:
    repo: "{{ mariadb_ppa }}"
    update_cache: yes
  register: result
  until: result is success
  retries: 3
  delay: 5

- name: Install MySQL client
  ansible.builtin.apt:
    name: "{{ mariadb_client_package }}"
    state: "{{ mariadb_client_package_state | default(apt_package_state) }}"
    update_cache: true

- name: Install and configure MariaDB server
  block:
    - name: Install MySQL server
      ansible.builtin.apt:
        name: "{{ mariadb_server_package }}"
        state: "{{ mariadb_server_package_state | default(apt_package_state) }}"
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Disable MariaDB binary logging
      ansible.builtin.template:
        src: disable-binary-logging.cnf
        dest: /etc/mysql/conf.d/disable-binary-logging.cnf
        owner: root
        group: root
        mode: "0644"
      when: mysql_binary_logging_disabled | bool
      notify: restart mysql server

    - name: Copy .my.cnf file with root password credentials
      ansible.builtin.template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: "0600"

    - name: Copy server config file with MariaDB optimisations
      ansible.builtin.template:
        src: 50-server.cnf.j2
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        mode: "0644"
      notify: restart mysql server

    - name: Set root user password
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        check_implicit_admin: true
        state: present
      no_log: true
      loop:
        - "{{ inventory_hostname }}"
        - "127.0.0.1"
        - "::1"
        - "localhost"

    - name: Delete anonymous MySQL server users
      community.mysql.mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      no_log: true
      loop:
        - "localhost"
        - "{{ inventory_hostname }}"
        - "{{ ansible_hostname }}"

    - name: Remove the test database
      community.mysql.mysql_db:
        name: test
        state: absent
      no_log: true

- name: Create additional mysql users
  ansible.builtin.import_tasks: additional-users.yml
  when: (wordpress_sites.items() | count) > (sites_using_remote_db | count)
  tags:
    - mariadb
    - mysql
    - mysql_additional_users