# Created by trellis-cli v1.17.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  simple-city.gr:
    site_hosts:
      - canonical: monk.gr
        redirects:
          - www.monk.gr
          
    local_path: ../site
    branch: local-new-setup
    repo: git@github.com:Giannisduke/eboy.gr.git
    repo_subtree_path: site
    wp_cli_path: web/wp
    multisite:
      enabled: true
      subdomains: true
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 30s
      skip_cache_uri: /wp-admin/|/wp-json/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml|/cart/|/checkout/|/my-account/|/wc-api/|/wp-admin/admin-ajax.php
      skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_
    env:
      WP_ENV: production
      MULTISITE: true
      SUBDOMAIN_INSTALL: true
      DOMAIN_CURRENT_SITE: simple-city.gr
      PATH_CURRENT_SITE: /
      SITE_ID_CURRENT_SITE: 1
      BLOG_ID_CURRENT_SITE: 1
      WP_HOME: https://monk.gr # hack to make sure WP_HOME is set to the primary domain
      WP_SITEURL: https://monk.gr/wp # hack to make sure WP_SITEURL is set to the primary domain